### ISSUE TITLE
add docker file to run app

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/neso-solar-consumer#13]
add docker file to run app, 

the last command could be to run `neso_solar_consumer/app.py` once #6 is done. 

Good to add CI, to make sure this can be built

**Comment by siddharth7113** [comment]
Hi @peterdudfield, I'd like to work on this! Here's my plan:

 1. Add a Dockerfile to build an image with Python 3.10 and `poetry` for dependencies.
2. Define the entry point to run `neso_solar_consumer.app`.
3. Test the Dockerfile locally.

> I'm new to Docker and CI but happy to learn! Let me know if you have any specific requirements or suggestions.

**Comment by peterdudfield** [comment]
Sounds good, I'd probably go python3.12

**Comment by peterdudfield** [comment]
Ci can be copied from https://github.com/openclimatefix/india-forecast-app/blob/main/.github/workflows/docker-build.yml

**Comment by siddharth7113** [comment]
Thanks for sharing the CI reference! I’ll start working on this issue
