### ISSUE TITLE
Add a `.gitignore` file to prevent tracking unnecessary files

### ISSUE THREAD

**Issue by siddharth7113** [openclimatefix/neso-solar-consumer#14]
## Detailed Description
Adding a `.gitignore` file would help prevent unnecessary files, such as build artifacts (`dist/`, `*.egg-info/`), Python cache files (`__pycache__/`), and test-related files (`.pytest_cache/`), from being tracked in the repository.

## Context
Including a `.gitignore` file will:
1. Keep the repository clean and focused on the source code.
2. Prevent contributors from accidentally committing autogenerated or temporary files.
3. Align the project with common best practices in Python development.

## Possible Implementation
Here’s a basic `.gitignore` tailored for this project:

```
# Python Bytecode
__pycache__/
*.py[cod]

# Virtual Environments
env/
venv/

# Build Artifacts
build/
dist/
*.egg-info/

# Pytest Cache
.pytest_cache/

# Logs
*.log
```

**Comment by peterdudfield** [comment]
THanks @siddharth7113 for adding this issue in
