### ISSUE TITLE
add MIT license

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/neso-solar-consumer#17]
Would be good to adda a MIT license to this repo

**Comment by peterdudfield** [comment]
If you fancy looking at some of our other OCF repos @Conor0Callaghan and if they have a license, then adding one?

**Comment by Conor0Callaghan** [comment]
> If you fancy looking at some of our other OCF repos @Conor0Callaghan and if they have a license, then adding one?

Sure no problem 🙂

**Comment by Conor0Callaghan** [comment]
> If you fancy looking at some of our other OCF repos @Conor0Callaghan and if they have a license, then adding one?

Is all code under the openclimatefix account MIT licensed @peterdudfield ?

**Comment by peterdudfield** [comment]
> > If you fancy looking at some of our other OCF repos @Conor0Callaghan and if they have a license, then adding one?
> 
> Is all code under the openclimatefix account MIT licensed @peterdudfield ?

where possible, there's a chance we have used some other license in other repos, but we might have also just forgotten to use some
