### ISSUE TITLE
Function to pull neso forecast

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/neso-solar-consumer#2]
Create a function to pull the NESO solar forecast

The url is here https://www.neso.energy/data-portal/embedded-wind-and-solar-forecasts/embedded_solar_and_wind_forecast

Would be great if the solar forecast are return as a pandas dataframe, with the following columns
- start_utc, 
- end_utc
- solar_forecast_kw

You can start of just by writing a script, and then make it into a function a bit later

Adding a test for this would be super good too

**Comment by peterdudfield** [comment]
@Seao7 would you be interested in this?

**Comment by Seao7** [comment]
Yeah I would be!

**Comment by Seao7** [comment]
@peterdudfield I have finished writing a script that has functions to fetch the required data. There are 2 functions - one for a simple API fetch and the other based on SQL Query fetch. Have also written a basic test function and compiled the code with Black. However, currently the repo - neso-solar-consumer is empty and option to Fork is unavailable. I am not really sure as to how I can proceed to create a pull request in this case.

**Comment by peterdudfield** [comment]
Hi @Seao7 , you should be able to pull now?

**Comment by Seao7** [comment]
Have created a pull request. Do let me know if it looks alright. @peterdudfield
