### ISSUE TITLE
wrap in app

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/neso-solar-consumer#6]
Wrap functions, into app, like app.py, we should
1. get forecast
2. format forecast
3. save forecast

**Comment by peterdudfield** [comment]
neso-solar-consumer/app.py, could be the file name

**Comment by siddharth7113** [comment]
Hi @peterdudfield, I’d like to start working on Issue #6 by creating a modular app.py file. I’ll include placeholders for the format forecast and save forecast functions until Issues #4 and #5 are complete. Let me know if that works!
